version: "3"
services:
    mongo:
        image: "mongo"
        environment:
            - MONGO_INITDB_DATABASE=mydb
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=p
        volumes:
            - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
        ports:
            - "27017-27019:27017-27019"
# https://medium.com/faun/managing-mongodb-on-docker-with-docker-compose-26bf8a0bbae3
